export const actionTypes = {
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN',
  INCREMENT_NUMBER: 'INCREMENT_NUMBER',
  DECREMENT_NUMBER: 'DECREMENT_NUMBER',
  FETCH_NEWS: 'FETCH_NEWS',
  FETCH_MESSAGE: 'FETCH_MESSAGE',
};
