export const actionTypes = {
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  INCREMENT_NUMBER: 'INCREMENT_NUMBER',
  DECREMENT_NUMBER: 'DECREMENT_NUMBER',
  FETCH_NEWS: 'FETCH_NEWS',
  FETCH_MESSAGE: 'FETCH_MESSAGE',
  POST_PROFILE: 'POST_PROFILE',
  FETCH_TREE: 'FETCH_TREE',
  FETCH_CERTIFICATE: 'FETCH_CERTIFICATE',
};
